<?php

// Copyright 2008-2011 Jonathan Brown


/**
 * Implements hook_permission().
 */
function storage_api_permission() {

  return array('administer storage' => array(
    'title' => t('Administer storage'),
//    'description' => t(''),
  ));
}


/**
 * Implements hook_menu().
 */
function storage_api_menu() {

  $items['system/storage/serve/%storage'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'storage_serve',
    'page arguments' => array(3),
    'access callback' => 'storage_access',
    'access arguments' => array(3),
  );
  

  $items['admin/structure/storage'] = array(
    'title' => 'Storage',
    'access arguments' => array('administer storage'),
    'description' => 'Configure storage.',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );


  $items['admin/structure/storage/containers'] = array(
    'title' => 'Containers',
    'description' => 'Configure storage containers.',
    'access arguments' => array('administer storage'),
    'page callback' => 'storage_containers',
    'weight' => 1,
    'file' => 'container.admin.inc',
  );
  
  $items['admin/structure/storage/containers/create'] = array(
    'title' => 'Create container',
    'access arguments' => array('administer storage'),
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_create_container_form'),
    'weight' => 1,
    'file' => 'container.admin.inc',
  );
  
  $items['admin/structure/storage/containers/%storage_container'] = array(
    'title callback' => 'storage_container_title',
    'title arguments' => array(4),
    'access arguments' => array('administer storage'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_form', 4),
    'file' => 'container.admin.inc',
  );

  $items['admin/structure/storage/containers/%storage_container/view'] = array(
    'title' => 'View',
    'access arguments' => array('administer storage'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
    'file' => 'container.admin.inc',
  );

  $items['admin/structure/storage/containers/%storage_container/edit'] = array(
    'title' => 'Edit',
    'access arguments' => array('administer storage'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_edit_form', 4),
    'weight' => 1,
    'file' => 'container.admin.inc',
  );

  $items['admin/structure/storage/containers/%storage_container/suspend'] = array(
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_suspend_form', 4),
    'file' => 'container.admin.inc',
  );
  
  $items['admin/structure/storage/containers/%storage_container/unsuspend'] = array(
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_unsuspend_form', 4),
    'file' => 'container.admin.inc',
  );
  
  $items['admin/structure/storage/containers/%storage_container/drain'] = array(
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_drain_form', 4),
    'file' => 'container.admin.inc',
  );

  $items['admin/structure/storage/containers/%storage_container/destroy'] = array(
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_container_destroy_form', 4),
    'file' => 'container.admin.inc',
  );


  $items['admin/structure/storage/classes'] = array(
    'title' => 'Classes',
    'description' => 'Configure storage classes.',
    'access arguments' => array('administer storage'),
    'page callback' => 'storage_classes_list',
    'weight' => 2,
    'file' => 'class.admin.inc',
  );

  $items['admin/structure/storage/classes/create'] = array(
    'title' => 'Create',
    'access arguments' => array('administer storage'),
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_create_class_form'),
    'weight' => 1,
    'file' => 'class.admin.inc',
  );

  $items['admin/structure/storage/classes/%storage_class'] = array(
    'title callback' => 'storage_class_title',
    'title arguments' => array(4),
    'access arguments' => array('administer storage'),
    'page callback' => 'storage_class',
    'page arguments' => array(4),
    'file' => 'class.admin.inc',
  );
  
  $items['admin/structure/storage/classes/%storage_class/view'] = array(
    'title' => 'View',
    'access arguments' => array('administer storage'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
    'file' => 'class.admin.inc',
  );
  
  $items['admin/structure/storage/classes/%storage_class/edit'] = array(
    'title' => 'Edit',
    'access arguments' => array('administer storage'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_class_edit_form', 4),
    'weight' => 1,
    'file' => 'class.admin.inc',
  );
  
  $items['admin/structure/storage/classes/%storage_class/destroy'] = array(
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_class_destroy_form', 4),
    'file' => 'class.admin.inc',
  );
  
  $items['admin/structure/storage/classes/%storage_class/add'] = array(
    'title' => 'Add container',
    'access arguments' => array('administer storage'),
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_class_add_container_form', 4),
    'weight' => 2,
    'file' => 'class.admin.inc',
  );
  
  $items['admin/structure/storage/classes/%storage_class/remove/%storage_container'] = array(
    'title' => 'Remove container',
    'access arguments' => array('administer storage'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('storage_class_remove_container_form', 4, 6),
    'file' => 'class.admin.inc',
  );

  return $items;
}


/**
 * Loads a storage.
 *
 * @param $storage_id
 *   The storage_id of the storage to be loaded.
 * @return
 *   The storage.
 */
function storage_load($storage_id) {

  try {
    return new Storage($storage_id);
  }
  catch (Exception $e) {
    return FALSE;
  }
}


/**
 * Loads a storage service.
 *
 * @param $srvice_id
 *   The service_id of the service to be loaded.
 * @return
 *   The service.
 */
function storage_service_load($service_id) {

  return new StorageService($service_id);
}


function storage_service_title(StorageService $service) {

  return $service->name();
}


/**
 * Loads a storage container.
 *
 * @param $container_id
 *   The container_id of the container to be loaded.
 * @return
 *   The container.
 */
function storage_container_load($container_id) {

  $fields = db_select('storage_container')
    ->fields('storage_container')
    ->condition('container_id', $container_id)
    ->execute()
    ->fetchAssoc();

  if (!$fields) {
    return FALSE;
  }
  
  return storage_container_new($fields);
}


function storage_container_new($fields, $unserialize = TRUE) {

  if ($unserialize) {
    $fields['settings'] = unserialize($fields['settings']);
  }
  
  $class = storage_container_class($fields['service_id']);
  return new $class($fields);
}


function storage_container_title(StorageContainer $container) {

  return $container->name();
}


/**
 * Loads a storage class.
 *
 * @param $class_id
 *   The class_id of the class to be loaded.
 * @return
 *   The class.
 */
function storage_class_load($class_id) {

  try {
    return new StorageClass($class_id);
  }
  catch (Exception $e) {
    return FALSE;
  }
}


function storage_class_title(StorageClass $class) {

  return $class->name();
}


function storage_selector($arg0, $arg1 = NULL) {

  return new StorageSelector($arg0, $arg1);
}


function storage_api_storage_services() {

  $services = array(
    'db' => array(
      'name' => t('Database'),
      'class' => 'StorageDB',
      'local' => FALSE,
      'direct' => TRUE,
      'can_copy' => FALSE,
      'serve_secure' => FALSE,
      'htaccess' => FALSE,
    ),
    'fs' => array(
      'name' => t('Filesystem'),
      'class' => 'StorageFS',
      'local' => TRUE,
      'direct' => FALSE,
      'can_copy' => FALSE,
      'serve_secure' => FALSE,
      'htaccess' => TRUE,
    ),
    'ftp' => array(
      'name' => t('FTP'),
      'class' => 'StorageFTP',
      'local' => FALSE,
      'direct' => FALSE,
      'can_copy' => FALSE,
      'serve_secure' => FALSE,
      'htaccess' => TRUE,
    ),
    'rackspace' => array(
      'name' => t('Rackspace Cloud Files'),
      'class' => 'StorageRackspace',
      'local' => FALSE,
      'direct' => FALSE,
      'can_copy' => FALSE,
      'serve_secure' => FALSE,
      'htaccess' => FALSE,
    ),
    's3_cloudfront' => array(
      'name' => t('Amazon S3 / CloudFront'),
      'class' => 'StorageS3CloudFront',
      'local' => FALSE,
      'direct' => FALSE,
      'can_copy' => FALSE,
//      'can_copy' => TRUE,
      'serve_secure' => TRUE,
      'htaccess' => FALSE,
    ),
  );

  return $services;
}


function storage_service_info($service_id = NULL) {

  $services = module_invoke_all('storage_services');
  
  if (empty($service_id)) {
    return $services;
  }
  else {
    return $services[$service_id];
  }
}


function storage_container_class($service_id) {

  $info = storage_service_info($service_id);
  return $info['class'];
}


function storage_serve(Storage $storage) {
  $storage->serve();
}


/**
 * Determine whether the user has access to a storage.
 *
 * @param $storage
 *   The storage that access is being checked for.
 * @return
 *   Boolean TRUE if the current user has access to the storage.
 */
function storage_access(Storage $storage) {
  return $storage->access();
}


function _storage_service_unavailable() {
  drupal_deliver_page(MENU_SITE_OFFLINE);
}


function storage_api_mime_detect($filepath, $filename) {
  $filepath = drupal_realpath($filepath);
  $mime = FALSE;

  if (extension_loaded('fileinfo')) {
    $finfo = &drupal_static(__FUNCTION__);

    if (!isset($finfo)) {
      $finfo = @finfo_open(FILEINFO_MIME);
    }

    if ($finfo !== FALSE) {
      $mime = finfo_file($finfo, $filepath);
    }
  }

  if ($mime == '' || (strtok($mime, ';') == 'application/octet-stream')) {
    // On OSX the -i switch is -I, so if we use the long flags everyone is
    // happy.
    $command = 'file --brief --mime ' . escapeshellarg($filepath);
    $mime = trim(exec($command, $output, $result));

    if ($result !== 0) {
      $mime = FALSE;
    }
  }

  if ($mime == '' || (strtok($mime, ';') == 'application/octet-stream')) {
    $mime = file_get_mimetype($filename);
  }

  return ($mime == '') ? 'application/octet-stream; charset=binary' : $mime;
}


function _storage_api_file_id($filepath, $filename, &$new_file = NULL) {

  $fileinfo = @stat($filepath);
  
  if (!$fileinfo) {
    return FALSE;
  }

  $md5 = hash_file('md5', $filepath, TRUE);
  
  $txn = db_transaction();
  $file_id = db_select('storage_file')
    ->fields('storage_file', array('file_id'))
    ->condition('filename', $filename)
    ->condition('size', $fileinfo['size'])
    ->condition('md5', $md5)
    ->execute()
    ->fetchField();

  if ($file_id === FALSE) {
  
    $file = array(
      'filename' => $filename,
      'size' => $fileinfo['size'],
      'md5' => $md5,
      'mimetype' => storage_api_mime_detect($filepath, $filename),
    );

    drupal_write_record('storage_file', $file);

    $file_id = $file['file_id'];
    $new_file = TRUE;
  }
  
  return $file_id;
}


function _storage_acquire_from_url($url) {

  $filepath = tempnam(file_directory_temp(), '');
  $fp = fopen($filepath, "w");

  $options = array(
    CURLOPT_FOLLOWLOCATION => TRUE,
    CURLOPT_AUTOREFERER => TRUE,
    CURLOPT_CONNECTTIMEOUT => 30,
    CURLOPT_LOW_SPEED_LIMIT => 256,
    CURLOPT_LOW_SPEED_TIME => 60,
    CURLOPT_FILE => $fp
  );

  $ch = curl_init(str_replace(' ', '+', $url));   // this seems to keep everyone happy
  curl_setopt_array($ch, $options);
  $result = curl_exec($ch);
  fclose ($fp);
  $info = curl_getinfo($ch);
  curl_close($ch);
  
  switch ((int)($info['http_code'] / 100)) {
  
    case 2:
      return $filepath;
      
    case 4:
      @unlink($filepath);
      return FALSE;         // hard failure
      
    default:
      @unlink($filepath);
      return NULL;          // soft failure
  }
}


function _storage_delete_file_if_unrequired($file_id) {
  $txn = db_transaction();
  
  // do any storages use this file?
  
  if (db_select('storage')
    ->condition('file_id', $file_id)
    ->countQuery()
    ->execute()
    ->fetchField())
  {
    return;
  }
  
  db_delete('storage_file')
    ->condition('file_id', $file_id)
    ->execute();
}


function _storage_get_service_names() {

  foreach (module_invoke_all('storage_services') as $service_id => $info) {
    $names[$service_id] = $info['name'];
  }
    
  asort($names);
  
  return $names;
}


function _storage_bcmath() {

  // crappy bcmath replacements

  if (!function_exists('bcdiv')) {
  
    function bcdiv($left_operand, $right_operand, $scale = 0) {
      return round($left_operand / $right_operand, $scale);
    }
  }

  if (!function_exists('bccomp')) {
  
    function bccomp($left_operand, $right_operand, $scale = 0) {
      if ($left_operand == $right_operand)
        return 0;
        
      if ($left_operand > $right_operand)
        return 1;
        
      return -1;
    }
  }
}


/**
 * Format a byte count to make it easy to read.
 *
 * See http://en.wikipedia.org/wiki/Kilobyte .
 *
 * @param $count
 *   Byte count to be formatted.
 * @return
 *   Formatted size.
 */
function storage_format_size($count) {
  _storage_bcmath();

  if (bccomp($count, 1000) < 0) {
    return format_plural((int)$count, '1 byte', '@count bytes');
  }
  
  $count = bcdiv($count, 1000, 2);
  $u = 0;
  
  while (bccomp($count, 1000) >= 0) {

    $count = bcdiv($count, 1000, 2);
    $u++;
  }

  $units = array('kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
  
  return $count . ' ' . $units[$u];
}


/**
 * Implements hook_theme().
 */
function storage_api_theme($existing, $type, $theme, $path) {

  return array(
    'storage_class_edit_form' => array(
      'render element' => 'form',
    ),
    'storage_info_table' => array(
      'render element' => 'info',
    ),
  );
}


function theme_storage_info_table($variables) {
  $rows = array();

  foreach ($variables['info'] as $key => $value) {
    $rows[] = array(
      array(
        'data' => $key . ':',
        'style' => 'font-weight: bold',
      ),
      $value,
    );
  }
  
  return '<p>' . theme('table', array(
    'rows' => $rows, 
    'attributes' => array('style' => 'width: auto;')
  )) . '</p>';
}


function storage_api_new_local_storage_path() {

  return file_create_filename('storage', conf_path());
}


/**
 * Implements hook_cron().
 */
function storage_api_cron() {

  $path = drupal_get_path('module', 'storage_api');
  require_once DRUPAL_ROOT . '/' . $path . '/cron.inc';

  _storage_api_cron();
}

