<?php
// $Id$

// Copyright 2008-2009 Jonathan Brown


/**
 * Implement hook_storage_service_info() .
 */
function storage_db_storage_service_info() {
  
  $info = array(
    'name' => t('Database'),
    'local' => FALSE,
    'direct' => TRUE,
    'can_copy' => FALSE,
  );
  
  return $info;
}


/**
 * Implement hook_storage_container_settings_form() .
 */
function storage_db_storage_container_settings_form($container, $edit) {
  global $db_url;
  
  if (is_array($db_url)) {
  
    foreach ($db_url as $key => $url)
      $options[$key] = $key;
  
    $items['db'] = array(
      '#type' => 'select',
      '#title' => t('Database'),
      '#options' => $options,
      '#required' => TRUE,
      '#validated' => TRUE,
      '#default_value' => isset($container->settings['db']) ? $container->settings['db'] : NULL,
    );
  }
  else {
    $items['#db'] = 'default';
  }

  $items['table'] = array(
    '#type' => 'textfield',
    '#title' => t('Table'),
    '#description' => t('Without prefix or {}, e.g. \'storage_contents\'.'),
    '#required' => TRUE,
    '#validated' => TRUE,
    '#default_value' => isset($container->settings['table']) ? $container->settings['table'] : NULL,
  );
  
  return $items;
}


/**
 * Implement hook_storage_container_validate() .
 */
function storage_db_storage_container_validate($container, $edit) {

  if(!$container->settings['table']) {
    form_set_error('settings][path', t('Database table field is required.'));
  }
}


/**
 * Implement hook_storage_container_create() .
 */
function storage_db_storage_container_create($container) {

  db_set_active($container->settings['db']);
  
  $success = db_query("
    CREATE TABLE {%s} (
      object_id INT UNSIGNED NOT NULL,
      contents LONGBLOB NOT NULL,
      PRIMARY KEY (object_id)
    )
  ",
    $container->settings['table']
  );
  
  db_set_active();
}


/**
 * Implement hook_storage_container_info() .
 */
function storage_db_storage_container_info($container) {

  if($container['settings']['db'])
    $info[t('Database')] = $container->settings['db'];
    
  $info[t('Table')] = $container->settings['table'];

  return $info;
}


/**
 * Implement hook_storage_container_destroy() .
 */
function storage_db_storage_container_destroy($container) {
  
  db_set_active($container->settings['db']);

  $success = db_query("  
    DROP TABLE {%s}
  ",
    $container->settings['table']
  );
  
  db_set_active();
  
  return $success;
}


/**
 * Implement hook_storage_instance_create() .
 */
function storage_db_storage_instance_create($container, $storage) {
  
  db_set_active($container->settings['db']);
  
  $success = db_query("
    INSERT INTO {%s}
    SET object_id = %d,
      contents = 0x%s
  ",
    $container->settings['table'],
    $storage->object_id,
    bin2hex(file_get_contents($storage->filepath))
  );
  
  db_set_active();
  
  return $success;
}


/**
 * Implement hook_storage_instance_destroy() .
 */
function storage_db_storage_instance_destroy($container, $storage, $reference) {
  
  db_set_active($container->settings['db']);
  
  $success = db_query("
    DELETE FROM {%s}
    WHERE object_id = %d
  ",
    $container->settings['table'],
    $storage->object_id
  );

  db_set_active();
  
  return $success;
}


/**
 * Implement hook_storage_instance_get_filepath() .
 */
function storage_db_storage_instance_get_filepath($container, $storage, $reference) {
  
  $filepath = tempnam(file_directory_temp(), '');
  
  db_set_active($container->settings['db']);

  $success = file_put_contents($filepath,
    db_result(db_query("
      SELECT contents
      FROM {%s}
      WHERE object_id = %d
    ",
      $container->settings['table'],
      $storage->object_id
    ))
  );

  db_set_active();
  
  if(!$success) {
    @unlink($filepath);
    return FALSE;
  }

  return $filepath;
}


/**
 * Implement hook_storage_instance_serve() .
 */
function storage_db_storage_instance_serve($container, $storage, $reference) {
  $storage->set_http_headers();
  
  db_set_active($container->settings['db']);

  echo db_result(db_query("
    SELECT contents
    FROM {%s}
    WHERE object_id = %d
  ",
    $container->settings['table'],
    $storage->object_id
  ));
  
  exit();
}

